### ISSUE TITLE
Root at carlinkit device

### ISSUE THREAD

**Issue by Zubastic** [segfly/carlinkit-modding#2]
Hello, I having different device c2w (https://cn.carlinkit.com/c2w).
Sometimes it starts fuzzing so making me mad. I want to unpack firmware and modify it. 
First of all I asked my friends to take flash rom from 2 devices (same software, but different sellers). When I unpacked it, I was sad because jffs2 encyption was customised and I couldn't extract data from file system. I know that it is custom zlib implementation with some differences, but without driver that implement that encoding I couldn't decode files. So I need help with that.

**Comment by segfly** [comment]
@Zubastic Unfortunately, I never tried to directly read the filesystem from the device. Instead, I viewed the filesystem extracted from ludwig-v's files, and also directly using the ssh package ludwig-v provided.

Sorry I can't be much more help, I don't have the device you do and I never tried to overcome the JFFS2 encryption. I recommend opening an issue in [ludwig-v's repo](https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering).
